<script setup lang="ts">
import { ref } from "vue";
import { useReveal } from "../composables/useReveal";

defineProps<{
  title: string;
  description: string;
  contractLabel: string;
  angularLabel: string;
  nestLabel: string;
  zodLabel: string;
  generateBadge: string;
}>();

const CONTRACT_CODE = `{
  "getUser": {
    "method": "GET",
    "path": "/users/:id",
    "params": { "id": "string" },
    "response": {
      "200": { "id": "string", "email": "string" },
      "404": { "message": "string" }
    }
  }
}`;

const ANGULAR_CODE = `// Auto-generated by contract-kit
import type { HttpClient } from "@angular/common/http";
import type { Observable } from "rxjs";
import type { ContractModel } from "./contract-model";

export type UsersGetUserResponse =
  ContractModel["users.getUser"]["response"]["200"];

export class ContractKitClient {
  constructor(
    private readonly http: HttpClient,
    private readonly baseUrl = ""
  ) {}

  users_getUser(
    input: ContractModel["users.getUser"]
  ): Observable<UsersGetUserResponse> {
    return this.request("GET", "/users/:id", input);
  }
}`;

const NESTJS_CODE = `// Auto-generated by contract-kit
import { Controller, Get } from "@nestjs/common";

@Controller("")
export class ContractController {
  @Get("/users/:id")
  users_getUser() {
    throw new Error("Not implemented");
  }
}`;

const ZOD_CODE = `// Auto-generated by contract-kit
import { z } from "zod";

export const zodSchemas = {
  "users.getUser": {
    params: z.object({ id: z.string() }),
    response: {
      "200": z.object({ id: z.string(), email: z.string() }),
      "404": z.object({ message: z.string() }),
    },
  },
} as const;`;

type TabId = "contract" | "angular" | "nestjs" | "zod";

const activeTab = ref<TabId>("contract");

const tabData: Record<TabId, { lang: string; file: string; code: string }> = {
  contract: { lang: "json", file: "contracts/users.contract.json", code: CONTRACT_CODE },
  angular:  { lang: "ts",   file: "generated/angular-client.ts",   code: ANGULAR_CODE },
  nestjs:   { lang: "ts",   file: "generated/nest-controller.ts",  code: NESTJS_CODE },
  zod:      { lang: "ts",   file: "generated/zod-schemas.ts",      code: ZOD_CODE },
};

const copied = ref(false);
let copiedTimer: ReturnType<typeof setTimeout> | undefined;

async function copyCode(): Promise<void> {
  const code = tabData[activeTab.value].code;
  try {
    await navigator.clipboard.writeText(code);
  } catch {
    const textarea = document.createElement("textarea");
    textarea.value = code;
    textarea.style.position = "absolute";
    textarea.style.left = "-9999px";
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
  }
  copied.value = true;
  if (copiedTimer) clearTimeout(copiedTimer);
  copiedTimer = setTimeout(() => { copied.value = false; }, 1200);
}

const titleRef = useReveal(0);
</script>

<template>
  <section id="see-it-in-action" class="mt-12">
    <h2
      ref="titleRef"
      class="reveal mb-2 font-heading text-2xl text-[color:var(--vp-c-text-1)] md:text-3xl"
    >
      {{ title }}
    </h2>
    <p class="mb-6 max-w-4xl text-[color:var(--vp-c-text-2)]">
      {{ description }}
    </p>

    <div
      class="landing-card min-w-0 overflow-hidden rounded-2xl border border-[color:var(--vp-c-bg-alt)] bg-[color:var(--vp-c-bg-soft)] shadow-card"
    >
      <!-- Tab bar -->
      <div
        class="flex flex-wrap items-center gap-1 border-b border-[color:var(--vp-c-bg-alt)] bg-[#070707] px-3 py-2"
      >
        <button
          type="button"
          :class="[
            'rounded-lg px-3 py-1.5 text-xs font-semibold transition',
            activeTab === 'contract'
              ? 'bg-accent text-[#1f1f1f]'
              : 'text-[#888] hover:text-[#ffffff]',
          ]"
          @click="activeTab = 'contract'"
        >
          {{ contractLabel }}
        </button>

        <span class="flex items-center gap-1 px-1 text-[10px] text-[#555]">
          <span>→</span>
          <span class="font-mono text-[#d2ff00]">{{ generateBadge }}</span>
          <span>→</span>
        </span>

        <button
          type="button"
          :class="[
            'rounded-lg px-3 py-1.5 text-xs font-semibold transition',
            activeTab === 'angular'
              ? 'bg-accent text-[#1f1f1f]'
              : 'text-[#888] hover:text-[#ffffff]',
          ]"
          @click="activeTab = 'angular'"
        >
          {{ angularLabel }}
        </button>
        <button
          type="button"
          :class="[
            'rounded-lg px-3 py-1.5 text-xs font-semibold transition',
            activeTab === 'nestjs'
              ? 'bg-accent text-[#1f1f1f]'
              : 'text-[#888] hover:text-[#ffffff]',
          ]"
          @click="activeTab = 'nestjs'"
        >
          {{ nestLabel }}
        </button>
        <button
          type="button"
          :class="[
            'rounded-lg px-3 py-1.5 text-xs font-semibold transition',
            activeTab === 'zod'
              ? 'bg-accent text-[#1f1f1f]'
              : 'text-[#888] hover:text-[#ffffff]',
          ]"
          @click="activeTab = 'zod'"
        >
          {{ zodLabel }}
        </button>
      </div>

      <!-- File label + copy -->
      <div
        class="flex items-center justify-between gap-2 border-b border-[color:var(--vp-c-bg-alt)] bg-[#0d0d0d] px-3 py-1.5 text-xs text-[#888]"
      >
        <span class="min-w-0 truncate font-mono">{{ tabData[activeTab].file }}</span>
        <div class="flex shrink-0 items-center gap-2">
          <span class="font-mono uppercase tracking-wide text-accent">{{ tabData[activeTab].lang }}</span>
          <button
            type="button"
            class="rounded-md border border-[#2a2a2a] bg-[#2a2a2a] px-2 py-1 text-xs font-semibold text-[#d2ff00] transition hover:border-accent hover:brightness-110"
            @click="copyCode"
          >
            {{ copied ? "Copied" : "Copy" }}
          </button>
        </div>
      </div>

      <!-- Code -->
      <pre
        class="m-0 max-h-72 overflow-auto bg-[#070707] p-4 text-sm leading-relaxed"
      ><code class="font-mono text-[#e8e8e8]">{{ tabData[activeTab].code }}</code></pre>
    </div>
  </section>
</template>
