import fs from "node:fs";
import path from "node:path";

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
export type ContractScalarType = "string" | "number" | "boolean" | "unknown";
export type ContractShape = Record<string, ContractScalarType>;
export type ContractResponses = Record<string, ContractShape>;

export type ContractEndpoint = {
  method: HttpMethod;
  path: string;
  params?: ContractShape;
  query?: ContractShape;
  body?: ContractShape;
  response?: ContractResponses;
};

export type ContractFile = Record<string, ContractEndpoint>;

export type SummaryEndpoint = {
  file: string;
  name: string;
  method: HttpMethod;
  path: string;
};

export type ContractSummary = {
  version: 1;
  endpoints: SummaryEndpoint[];
};

const METHOD_SET = new Set<HttpMethod>(["GET", "POST", "PUT", "PATCH", "DELETE"]);
const SCALAR_SET = new Set<ContractScalarType>(["string", "number", "boolean", "unknown"]);
const STATUS_CODE_PATTERN = /^[1-5][0-9][0-9]$/;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function validateShape(shape: unknown, label: string): void {
  if (!isRecord(shape)) {
    throw new Error(`Invalid ${label}: expected an object`);
  }

  for (const [field, fieldType] of Object.entries(shape)) {
    if (typeof fieldType !== "string" || !SCALAR_SET.has(fieldType as ContractScalarType)) {
      throw new Error(
        `Invalid ${label}.${field}: type must be one of ${Array.from(SCALAR_SET).join(", ")}`
      );
    }
  }
}

function validateResponseShapes(response: unknown, label: string): void {
  if (!isRecord(response)) {
    throw new Error(`Invalid ${label}: expected an object`);
  }

  for (const [statusCode, shape] of Object.entries(response)) {
    if (!STATUS_CODE_PATTERN.test(statusCode)) {
      throw new Error(`Invalid ${label}.${statusCode}: status code must be a 3-digit HTTP code`);
    }
    validateShape(shape, `${label}.${statusCode}`);
  }
}

export function validateContract(contract: unknown, sourceName = "unknown"): asserts contract is ContractFile {
  if (!isRecord(contract)) {
    throw new Error(`Invalid contract in ${sourceName}: contract must be an object`);
  }

  const entries = Object.entries(contract);
  if (entries.length === 0) {
    throw new Error(`Invalid contract in ${sourceName}: contract has no endpoints`);
  }

  for (const [endpointName, endpoint] of entries) {
    if (!isRecord(endpoint)) {
      throw new Error(`Invalid endpoint "${endpointName}" in ${sourceName}: endpoint must be an object`);
    }

    if (typeof endpoint.path !== "string" || endpoint.path.length === 0) {
      throw new Error(`Invalid endpoint "${endpointName}" in ${sourceName}: "path" must be a non-empty string`);
    }

    if (typeof endpoint.method !== "string" || !METHOD_SET.has(endpoint.method as HttpMethod)) {
      throw new Error(
        `Invalid endpoint "${endpointName}" in ${sourceName}: "method" must be one of ${Array.from(METHOD_SET).join(", ")}`
      );
    }

    if ("params" in endpoint) {
      validateShape(endpoint.params, `endpoint "${endpointName}".params`);
    }

    if ("query" in endpoint) {
      validateShape(endpoint.query, `endpoint "${endpointName}".query`);
    }

    if ("body" in endpoint) {
      validateShape(endpoint.body, `endpoint "${endpointName}".body`);
    }

    if ("response" in endpoint) {
      validateResponseShapes(endpoint.response, `endpoint "${endpointName}".response`);
    }
  }
}

export function readContract(filePath: string): ContractFile {
  const raw = fs.readFileSync(filePath, "utf8");
  const parsed: unknown = JSON.parse(raw);
  validateContract(parsed, filePath);
  return parsed;
}

export function scanContractFiles(projectRoot: string): string[] {
  const contractsDir = path.join(projectRoot, "contracts");
  if (!fs.existsSync(contractsDir)) {
    throw new Error(`Missing contracts directory: ${contractsDir}`);
  }

  return fs
    .readdirSync(contractsDir)
    .filter((file) => file.endsWith(".contract.json"))
    .map((file) => path.join(contractsDir, file));
}

export function createSummary(contractsByFile: Record<string, ContractFile>): ContractSummary {
  const endpoints: SummaryEndpoint[] = [];
  for (const [file, contract] of Object.entries(contractsByFile)) {
    for (const [name, endpoint] of Object.entries(contract)) {
      endpoints.push({
        file: path.basename(file),
        name,
        method: endpoint.method,
        path: endpoint.path
      });
    }
  }

  endpoints.sort((a, b) => `${a.method} ${a.path}`.localeCompare(`${b.method} ${b.path}`));
  return { version: 1, endpoints };
}

function generateTypesFile(summary: ContractSummary): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by ngx-contract-kit");
  lines.push("");
  lines.push('export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";');
  lines.push("");
  lines.push("export type ContractEndpoint = {");
  lines.push("  name: string;");
  lines.push("  method: HttpMethod;");
  lines.push("  path: string;");
  lines.push("  source: string;");
  lines.push("};");
  lines.push("");
  lines.push("export const endpoints: ContractEndpoint[] = [");
  for (const endpoint of summary.endpoints) {
    lines.push(
      `  { name: "${endpoint.name}", method: "${endpoint.method}", path: "${endpoint.path}", source: "${endpoint.file}" },`
    );
  }
  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

function scalarToTsType(scalar: ContractScalarType): string {
  switch (scalar) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    default:
      return "unknown";
  }
}

function shapeToTypeLiteral(shape: ContractShape | undefined): string {
  if (!shape) {
    return "undefined";
  }
  const fields = Object.entries(shape).map(([key, scalar]) => `  ${key}: ${scalarToTsType(scalar)};`);
  if (fields.length === 0) {
    return "{}";
  }
  return `{\n${fields.join("\n")}\n}`;
}

export function generateContractModelFile(contractsByFile: Record<string, ContractFile>): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by ngx-contract-kit");
  lines.push("");
  lines.push('export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";');
  lines.push("");
  lines.push("export type ContractModel = {");

  const sortedFiles = Object.entries(contractsByFile).sort(([a], [b]) => a.localeCompare(b));
  for (const [, contract] of sortedFiles) {
    const endpoints = Object.entries(contract).sort(([a], [b]) => a.localeCompare(b));
    for (const [name, endpoint] of endpoints) {
      lines.push(`  "${name}": {`);
      lines.push(`    method: "${endpoint.method}";`);
      lines.push(`    path: "${endpoint.path}";`);
      lines.push(`    params: ${shapeToTypeLiteral(endpoint.params)};`);
      lines.push(`    query: ${shapeToTypeLiteral(endpoint.query)};`);
      lines.push(`    body: ${shapeToTypeLiteral(endpoint.body)};`);
      lines.push("    response: {");
      if (endpoint.response && Object.keys(endpoint.response).length > 0) {
        const responses = Object.entries(endpoint.response).sort(([a], [b]) => a.localeCompare(b));
        for (const [statusCode, shape] of responses) {
          lines.push(`      "${statusCode}": ${shapeToTypeLiteral(shape)};`);
        }
      }
      lines.push("    };");
      lines.push("  };");
    }
  }

  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

export function writeGeneratedArtifacts(
  projectRoot: string,
  summary: ContractSummary,
  contractsByFile?: Record<string, ContractFile>
): void {
  const outputDir = path.join(projectRoot, "generated");
  fs.mkdirSync(outputDir, { recursive: true });

  const typesPath = path.join(outputDir, "types.ts");
  fs.writeFileSync(typesPath, generateTypesFile(summary), "utf8");

  const summaryPath = path.join(outputDir, "summary.json");
  fs.writeFileSync(summaryPath, JSON.stringify(summary, null, 2), "utf8");

  if (contractsByFile) {
    const contractModelPath = path.join(outputDir, "contract-model.ts");
    fs.writeFileSync(contractModelPath, generateContractModelFile(contractsByFile), "utf8");
  }
}

export function diffSummaries(
  previous: ContractSummary,
  current: ContractSummary
): { breaking: boolean; removed: string[] } {
  const prevSet = new Set(previous.endpoints.map((e) => `${e.method} ${e.path}`));
  const currentSet = new Set(current.endpoints.map((e) => `${e.method} ${e.path}`));

  const removed: string[] = [];
  for (const endpoint of prevSet) {
    if (!currentSet.has(endpoint)) {
      removed.push(endpoint);
    }
  }

  return {
    breaking: removed.length > 0,
    removed
  };
}
