const fs = require("fs");
const path = require("path");

const METHOD_SET = new Set(["GET", "POST", "PUT", "PATCH", "DELETE"]);

function validateContract(contract, sourceName = "unknown") {
  if (!contract || typeof contract !== "object" || Array.isArray(contract)) {
    throw new Error(`Invalid contract in ${sourceName}: contract must be an object`);
  }

  const entries = Object.entries(contract);
  if (entries.length === 0) {
    throw new Error(`Invalid contract in ${sourceName}: contract has no endpoints`);
  }

  for (const [endpointName, endpoint] of entries) {
    if (!endpoint || typeof endpoint !== "object" || Array.isArray(endpoint)) {
      throw new Error(`Invalid endpoint "${endpointName}" in ${sourceName}: endpoint must be an object`);
    }

    if (typeof endpoint.path !== "string" || endpoint.path.length === 0) {
      throw new Error(`Invalid endpoint "${endpointName}" in ${sourceName}: "path" must be a non-empty string`);
    }

    if (!METHOD_SET.has(endpoint.method)) {
      throw new Error(
        `Invalid endpoint "${endpointName}" in ${sourceName}: "method" must be one of ${Array.from(METHOD_SET).join(", ")}`
      );
    }
  }
}

function readContract(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  const parsed = JSON.parse(raw);
  validateContract(parsed, filePath);
  return parsed;
}

function scanContractFiles(projectRoot) {
  const contractsDir = path.join(projectRoot, "contracts");
  if (!fs.existsSync(contractsDir)) {
    throw new Error(`Missing contracts directory: ${contractsDir}`);
  }

  return fs
    .readdirSync(contractsDir)
    .filter((file) => file.endsWith(".contract.json"))
    .map((file) => path.join(contractsDir, file));
}

function createSummary(contractsByFile) {
  const endpoints = [];
  for (const [file, contract] of Object.entries(contractsByFile)) {
    for (const [name, endpoint] of Object.entries(contract)) {
      endpoints.push({
        file: path.basename(file),
        name,
        method: endpoint.method,
        path: endpoint.path
      });
    }
  }

  endpoints.sort((a, b) => `${a.method} ${a.path}`.localeCompare(`${b.method} ${b.path}`));
  return { version: 1, endpoints };
}

function generateTypesFile(summary) {
  const lines = [];
  lines.push("// Auto-generated by ngx-contract-kit");
  lines.push("");
  lines.push("export type HttpMethod = \"GET\" | \"POST\" | \"PUT\" | \"PATCH\" | \"DELETE\";");
  lines.push("");
  lines.push("export type ContractEndpoint = {");
  lines.push("  name: string;");
  lines.push("  method: HttpMethod;");
  lines.push("  path: string;");
  lines.push("  source: string;");
  lines.push("};");
  lines.push("");
  lines.push("export const endpoints: ContractEndpoint[] = [");
  for (const endpoint of summary.endpoints) {
    lines.push(
      `  { name: "${endpoint.name}", method: "${endpoint.method}", path: "${endpoint.path}", source: "${endpoint.file}" },`
    );
  }
  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

function writeGeneratedArtifacts(projectRoot, summary) {
  const outputDir = path.join(projectRoot, "generated");
  fs.mkdirSync(outputDir, { recursive: true });

  const typesPath = path.join(outputDir, "types.ts");
  fs.writeFileSync(typesPath, generateTypesFile(summary), "utf8");

  const summaryPath = path.join(outputDir, "summary.json");
  fs.writeFileSync(summaryPath, JSON.stringify(summary, null, 2), "utf8");
}

function diffSummaries(previous, current) {
  const prevSet = new Set(previous.endpoints.map((e) => `${e.method} ${e.path}`));
  const currentSet = new Set(current.endpoints.map((e) => `${e.method} ${e.path}`));

  const removed = [];
  for (const endpoint of prevSet) {
    if (!currentSet.has(endpoint)) {
      removed.push(endpoint);
    }
  }

  return {
    breaking: removed.length > 0,
    removed
  };
}

module.exports = {
  createSummary,
  diffSummaries,
  readContract,
  scanContractFiles,
  writeGeneratedArtifacts
};
