import path from "node:path";
import type { ContractFile, ContractScalarType, ContractShape } from "@fr4n0m/core";
import { z, type ZodTypeAny } from "zod";

function scalarToZodType(scalar: ContractScalarType): ZodTypeAny {
  switch (scalar) {
    case "string":
      return z.string();
    case "number":
      return z.number();
    case "boolean":
      return z.boolean();
    default:
      return z.unknown();
  }
}

export function createZodSchemaFromShape(shape: ContractShape | undefined): z.ZodObject<Record<string, ZodTypeAny>> {
  const fields: Record<string, ZodTypeAny> = {};
  for (const [field, scalar] of Object.entries(shape ?? {})) {
    fields[field] = scalarToZodType(scalar);
  }
  return z.object(fields);
}

function scalarToZodExpression(scalar: ContractScalarType): string {
  switch (scalar) {
    case "string":
      return "z.string()";
    case "number":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    default:
      return "z.unknown()";
  }
}

function shapeToZodExpression(shape: ContractShape | undefined): string {
  const entries = Object.entries(shape ?? {}).sort(([a], [b]) => a.localeCompare(b));
  if (entries.length === 0) {
    return "z.object({})";
  }
  const lines = entries.map(([field, scalar]) => `    ${field}: ${scalarToZodExpression(scalar)},`);
  return `z.object({\n${lines.join("\n")}\n  })`;
}

function contractNamespaceFromPath(contractFilePath: string): string {
  return path.basename(contractFilePath).replace(/\.contract\.json$/i, "");
}

export function generateZodSchemasSource(contractsByFile: Record<string, ContractFile>): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by contract-kit");
  lines.push("import { z } from \"zod\";");
  lines.push("");
  lines.push("export const zodSchemas = {");
  const sortedFiles = Object.entries(contractsByFile).sort(([a], [b]) => a.localeCompare(b));
  for (const [filePath, contract] of sortedFiles) {
    const namespace = contractNamespaceFromPath(filePath);
    const endpoints = Object.entries(contract).sort(([a], [b]) => a.localeCompare(b));
    for (const [endpointName, endpoint] of endpoints) {
      const key = `${namespace}.${endpointName}`;
      lines.push(`  "${key}": {`);
      lines.push(`    params: ${shapeToZodExpression(endpoint.params)},`);
      lines.push(`    query: ${shapeToZodExpression(endpoint.query)},`);
      lines.push(`    body: ${shapeToZodExpression(endpoint.body)},`);
      lines.push("    response: {");
      const sortedResponses = Object.entries(endpoint.response ?? {}).sort(([a], [b]) => a.localeCompare(b));
      for (const [status, shape] of sortedResponses) {
        lines.push(`      "${status}": ${shapeToZodExpression(shape)},`);
      }
      lines.push("    },");
      lines.push("  },");
    }
  }
  lines.push("} as const;");
  lines.push("");
  return lines.join("\n");
}
