import path from "node:path";
import type { ContractFile } from "@ngx-contract-kit/core";

export type ContractModelLike = Record<
  string,
  {
    method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
    path: string;
    params: unknown;
    query: unknown;
    body: unknown;
    response: Record<string, unknown>;
  }
>;

type ResponseUnion<TResponse extends Record<string, unknown>> = TResponse[keyof TResponse];

export type HandlerInput<TEndpoint extends ContractModelLike[string]> = {
  params: TEndpoint["params"];
  query: TEndpoint["query"];
  body: TEndpoint["body"];
};

export type HandlerOutput<TEndpoint extends ContractModelLike[string]> =
  | ResponseUnion<TEndpoint["response"]>
  | Promise<ResponseUnion<TEndpoint["response"]>>;

export type NestHandler<TEndpoint extends ContractModelLike[string]> = (
  input: HandlerInput<TEndpoint>
) => HandlerOutput<TEndpoint>;

export type NestHandlerMap<TModel extends ContractModelLike> = {
  [K in keyof TModel]: NestHandler<TModel[K]>;
};

export type EndpointRoute = {
  key: string;
  method: ContractModelLike[string]["method"];
  path: string;
};

function toNestDecorator(method: EndpointRoute["method"]): "Get" | "Post" | "Put" | "Patch" | "Delete" {
  switch (method) {
    case "GET":
      return "Get";
    case "POST":
      return "Post";
    case "PUT":
      return "Put";
    case "PATCH":
      return "Patch";
    case "DELETE":
      return "Delete";
  }
}

function toMethodName(contractKey: string): string {
  return contractKey.replace(/[^a-zA-Z0-9_$]/g, "_");
}

function contractNamespaceFromPath(contractFilePath: string): string {
  return path.basename(contractFilePath).replace(/\.contract\.json$/i, "");
}

export function defineNestHandlers<TModel extends ContractModelLike>(
  handlers: NestHandlerMap<TModel>
): NestHandlerMap<TModel> {
  return handlers;
}

export function createNestRouteTable<TModel extends ContractModelLike>(model: TModel): EndpointRoute[] {
  return Object.entries(model)
    .map(([key, endpoint]) => ({
      key,
      method: endpoint.method,
      path: endpoint.path
    }))
    .sort((a, b) => `${a.method} ${a.path}`.localeCompare(`${b.method} ${b.path}`));
}

export function createNestModelFromContracts(
  contractsByFile: Record<string, ContractFile>
): ContractModelLike {
  const model: ContractModelLike = {};
  const sortedFiles = Object.entries(contractsByFile).sort(([a], [b]) => a.localeCompare(b));
  for (const [filePath, contract] of sortedFiles) {
    const namespace = contractNamespaceFromPath(filePath);
    const endpoints = Object.entries(contract).sort(([a], [b]) => a.localeCompare(b));
    for (const [endpointName, endpoint] of endpoints) {
      const key = `${namespace}.${endpointName}`;
      model[key] = {
        method: endpoint.method,
        path: endpoint.path,
        params: endpoint.params ?? {},
        query: endpoint.query ?? {},
        body: endpoint.body ?? {},
        response: endpoint.response ?? {}
      };
    }
  }
  return model;
}

export function generateNestControllerSource<TModel extends ContractModelLike>(
  model: TModel,
  className = "ContractController"
): string {
  const routes = createNestRouteTable(model);
  const lines: string[] = [];
  lines.push("// Auto-generated by ngx-contract-kit");
  lines.push('import { Controller, Delete, Get, Patch, Post, Put } from "@nestjs/common";');
  lines.push("");
  lines.push('@Controller("")');
  lines.push(`export class ${className} {`);
  for (const route of routes) {
    const methodName = toMethodName(route.key);
    const decorator = toNestDecorator(route.method);
    lines.push(`  @${decorator}("${route.path}")`);
    lines.push(`  ${methodName}() {`);
    lines.push('    throw new Error("Not implemented");');
    lines.push("  }");
    lines.push("");
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function generateNestHandlersStubSource<TModel extends ContractModelLike>(model: TModel): string {
  const routes = createNestRouteTable(model);
  const lines: string[] = [];
  lines.push("// Auto-generated by ngx-contract-kit");
  lines.push('import { defineNestHandlers, type NestHandlerMap } from "@ngx-contract-kit/plugin-nestjs";');
  lines.push('import type { ContractModel } from "./contract-model";');
  lines.push("");
  lines.push("export const handlers = defineNestHandlers<ContractModel>({");
  for (const route of routes) {
    lines.push(`  "${route.key}": async (_input) => {`);
    lines.push(
      `    throw new Error("TODO: implement ${route.method} ${route.path} (${route.key})");`
    );
    lines.push("  },");
  }
  lines.push("});");
  lines.push("");
  lines.push("export type GeneratedHandlers = NestHandlerMap<ContractModel>;");
  lines.push("");
  return lines.join("\n");
}
